### PR TITLE
Create kubenav.yaml

### PR DESCRIPTION
**Pull request by si458**
this is a basic yaml file which can be used instead of helm with `kubectl create -f kubenav.yaml`

### CODE REVIEW

**Comment by si458** [comment]
can you make this accessible publicly please?

**Comment by ricoberger** [comment]
Hi @si458, I'm not sure if we really need this file. What is the difference to just running `kubectl apply --kustomize github.com/kubenav/deploy/kustomize` or `kubectl apply -f kustomize/`?

**Comment by si458** [comment]
Hi @ricoberger,
this was to help facilitate the install on the @civo kube100 clusters,
as they have kubectl installed in them but not the kustomize, so it required only a single yaml file
(or a direct https link to a yaml file)
it might also help others who only use yaml files and dont understand kustomize like myself

**Comment by ricoberger** [comment]
Mh I'm still not sure about the additional file. My biggest problem with it is that it is another file, which must be maintained and the same can be achieved by running the following commands:

```sh
kubectl apply -f kustomize/namespace.yaml
kubectl apply -f kustomize/clusterrole.yaml
kubectl apply -f kustomize/clusterrolebinding.yaml
kubectl apply -f kustomize/serviceaccount.yaml
kubectl apply -f kustomize/deployment.yaml
kubectl apply -f kustomize/service.yaml
```

**Comment by si458** [comment]
Hmmm ok don't worry about this file then
As is I managed to get the k3s helm cattle.io yaml working!?

**Pull request closed without merging**
